### PR TITLE
feat: add documentation for input and image

### PR DESCRIPTION
**Pull request by Aazam10**
Hi I have added documentation for image and input component.

CSB Input : https://5y4ku.csb.app/input/input.html
CSB Image: https://5y4ku.csb.app/image.html

Please review.

### CODE REVIEW

**Review by VishalPatil18 — APPROVED** [review]
The code looks quite clean and also works well. Just one suggestion that you could make your sidebar and navbar fixed as that helps in better UX. Only the content body will scroll that has all the code samples and examples.

**Review by starver20 — APPROVED** [review]

**Review by sagar455 — APPROVED** [review]
Looks good

**Comment by Aazam10** [comment]
> The code looks quite clean and also works well. Just one suggestion that you could make your sidebar and navbar fixed as that helps in better UX. Only the content body will scroll that has all the code samples and examples.

**Comment by Aazam10** [comment]
I will do that at the end vishal. Thanks for the suggestion will keep that in mind when I am finalising everything

**Pull request merged**
