### PR TITLE
feat:add introduction

### PR DESCRIPTION
**Pull request by Aazam10**
Hi I have added installation and introduction please review

### CODE REVIEW

**Comment by Aazam10** [comment]
codesandbox link: https://78ebe.csb.app/usage.html

**Review by VishalPatil18 — CHANGES_REQUESTED** [review]
The code looks clean and works well. Just one suggestion that the code is not visible properly here. Maybe you might need to fix this.
Screenshot 2022-02-02 at 14 51 24

**Comment by VishalPatil18** [comment]
> The code looks clean and works well. Just one suggestion that the code is not visible properly here. Maybe you might need to fix this. Screenshot 2022-02-02 at 14 51 24

You might need to change the width of the iframe or its parent class.

**Review by mohammed-sas — APPROVED** [review]
other than suggested by vishal your pr is good to merge

**Comment by Aazam10** [comment]
https://03l8p.csb.app/usage.html

**Comment by Aazam10** [comment]
Hi vishal i have made the changes can you check and approve

**Review by VishalPatil18 — APPROVED** [review]

**Pull request merged**
